
version: '3.3'
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=r00t
    container_name: ps-core-db
    ports:
      - "5432:5432"

  web:
    container_name: web
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"

    restart: always

    depends_on:
      - ps-core-db




        ###############################################
#        version: '3.3'
#        services:
#          db:
#            container_name: msql
#            image: mysql:5.7
#            environment:
#              - MYSQL_ROOT_PASSWORD=r00t
#            ports:
#              - "3306:3306"
#          web:
#            container_name: web
#            build:
#              dockerfile: Dockerfile
#              context: .
#            ports:
#              - "8080:8080"
#            environment:
#              - MYSQL_ROOT_PASSWORD=r00t
#              - MYSQL_ROOT_USERNAME=r00t
#              - START_DELAY=20000
#            depends_on:
#              - msql
