
version: '3.3'
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=r00t
    container_name: micro-db
    ports:
      - "5432:5432"

  web:
    container_name: micro-web
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - micro-db



